debug: true
management:
    endpoint:
        configprops:
            show-values: always
        env:
            show-values: always
        restart:
            enabled: true
    endpoints:
        jmx:
            exposure:
                include: '"*"'
        web:
            exposure:
                include: '*'
server:
    tomcat:
        accept-count: 1
        threads:
            max: 1
spring:
    application:
        name: demo2
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
time:
    send:
        sms: 5000
